create schema if not exists cw;

create table if not exists cw.conversation_label_events (
    id bigint generated by default as identity primary key,
    chatwoot_conversation_id bigint not null,
    previous_labels text[] not null default '{}'::text[],
    next_labels text[] not null default '{}'::text[],
    added_labels text[] not null default '{}'::text[],
    removed_labels text[] not null default '{}'::text[],
    event_source text not null default 'sync_diff',
    occurred_at timestamp with time zone not null default now(),
    detected_at timestamp with time zone not null default now(),
    raw_payload jsonb not null default '{}'::jsonb,
    event_key text unique,
    created_at timestamp with time zone not null default now(),
    constraint conversation_label_events_source_check
        check (event_source = any (array['dashboard', 'webhook', 'sync_diff', 'repair']))
);

create index if not exists conversation_label_events_conversation_idx
    on cw.conversation_label_events (chatwoot_conversation_id);

create index if not exists conversation_label_events_occurred_idx
    on cw.conversation_label_events (occurred_at);

create index if not exists conversation_label_events_added_gin_idx
    on cw.conversation_label_events using gin (added_labels);

create index if not exists conversation_label_events_removed_gin_idx
    on cw.conversation_label_events using gin (removed_labels);
