create schema if not exists cw;

create table if not exists cw.import_batches (
    id uuid primary key default gen_random_uuid(),
    file_name text not null,
    file_type text not null,
    source_system text not null default 'excel',
    row_count integer not null default 0,
    valid_count integer not null default 0,
    skipped_count integer not null default 0,
    create_count integer not null default 0,
    update_count integer not null default 0,
    status text not null default 'running'
        check (status = any (array['running', 'success', 'partial', 'error']::text[])),
    mapping jsonb not null default '{}'::jsonb,
    stats jsonb not null default '{}'::jsonb,
    error_message text,
    imported_by uuid references auth.users(id),
    imported_by_email text,
    started_at timestamp with time zone not null default now(),
    finished_at timestamp with time zone,
    created_at timestamp with time zone not null default now()
);

create table if not exists cw.import_batch_errors (
    id bigint generated by default as identity primary key,
    import_batch_id uuid references cw.import_batches(id) on delete cascade,
    row_number integer not null,
    severity text not null default 'error'
        check (severity = any (array['error', 'warning']::text[])),
    field_name text,
    reason text not null,
    raw_row jsonb not null default '{}'::jsonb,
    created_at timestamp with time zone not null default now()
);

alter table cw.conversations_current
    add column if not exists source_system text,
    add column if not exists external_lead_id text,
    add column if not exists import_batch_id uuid references cw.import_batches(id),
    add column if not exists imported_at timestamp with time zone,
    add column if not exists imported_by uuid references auth.users(id);

create index if not exists idx_cw_import_batches_started_at
    on cw.import_batches (started_at desc);

create index if not exists idx_cw_import_batch_errors_batch
    on cw.import_batch_errors (import_batch_id);

create index if not exists idx_cw_conversations_current_import_batch
    on cw.conversations_current (import_batch_id);

create unique index if not exists idx_cw_conversations_current_import_identity
    on cw.conversations_current (source_system, external_lead_id)
    where source_system is not null and external_lead_id is not null;

alter table cw.conversation_label_events
    drop constraint if exists conversation_label_events_source_check;

alter table cw.conversation_label_events
    add constraint conversation_label_events_source_check
    check (event_source = any (array['dashboard', 'webhook', 'sync_diff', 'repair', 'manual_import']::text[]));

alter table cw.import_batches enable row level security;
alter table cw.import_batch_errors enable row level security;

drop policy if exists authenticated_all on cw.import_batches;
create policy authenticated_all
    on cw.import_batches
    for all
    to authenticated
    using (true)
    with check (true);

drop policy if exists authenticated_all on cw.import_batch_errors;
create policy authenticated_all
    on cw.import_batch_errors
    for all
    to authenticated
    using (true)
    with check (true);

grant all on cw.import_batches to authenticated;
grant all on cw.import_batch_errors to authenticated;
grant usage, select on sequence cw.import_batch_errors_id_seq to authenticated;
